[package]
description = "Telemetry Service GRPC and REST servers"
edition     = "2021"                                                       # Allowed values are 2015, 2018, 2021
homepage    = "https://www.arrowair.com/docs/documentation/services/intro"
keywords    = ["vtol", "server", "telemetry"]                              # max 5
license     = "BUSL-1.1"
name        = "svc-telemetry"
repository  = "https://github.com/Arrow-air/svc-telemetry"
version     = "0.2.0-develop.2"

categories = [
  "aerospace::drones",
  "aerospace::protocols",
] # max 5 -- https://crates.io/category_slugs

[features]
vendored-openssl = ['openssl/vendored']

[dependencies]
axum          = "0.5"
cargo-husky   = "1"
chrono        = { version = "0.4", features = ["serde"] }
clap          = { version = "4.0", features = ["derive"] }
futures       = "0.3"
hyper         = "0.14"
lib-ccsds     = { git = "https://github.com/Arrow-air/lib-ccsds", branch = "develop" }
log           = "0.4"
openssl       = "0.10"
ordered-float = { version = "3.4", features = ["serde"] }
packed_struct = "0.10"
prost         = "0.11"
prost-build   = "0.11"
prost-types   = "0.11"
serde         = "1.0"
serde_json    = "1.0"
tokio         = { version = "1.20", features = ["full"] }
tokio-util    = "0.7"
tonic         = "0.8"
tonic-health  = "0.7"
uuid          = { version = "1.2", features = ["serde"] }

[dependencies.log4rs]
features = [
  "background_rotation",
  "rolling_file_appender",
  "json_format",
  "gzip",
]
version = "1.2"

[dependencies.utoipa]
features = ["axum_extras", "chrono"]
version  = "2.2"

[dev-dependencies.cargo-husky]
default-features = false          # Disable features which are enabled by default
features         = ["user-hooks"]
version          = "1"

[build-dependencies]
tonic-build = "0.8"
