[package]
edition = "2021"
name    = "svc-telemetry-client-rest"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono        = { version = "0.4", features = ["serde"] }
ordered-float = { version = "3.4", features = ["serde"] }
packed_struct = "0.10"
serde         = "1.0"
serde_json    = "1.0"
utoipa        = { version = "2.2", features = ["axum_extras"] }
uuid          = { version = "1.2", features = ["serde"] }

[[example]]
name = "rest"

[dev-dependencies]
hyper = { version = "0.14", features = ["full"] }
tokio = { version = "1.20", features = ["full"] }
