[package]
edition = "2021"
name    = "svc-telemetry-client-rest"
version = "0.0.1-develop.6"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
adsb_deku     = "0.6"
chrono        = { version = "0.4", features = ["serde"] }
mavlink       = "0.10"
ordered-float = { version = "3.4", features = ["serde"] }
packed_struct = "0.10"
serde         = "1.0"
serde_json    = "1.0"
utoipa        = { version = "2.2", features = ["axum_extras"] }
uuid          = { version = "1.2", features = ["serde"] }

[dependencies.svc-storage-client-grpc]
git = "https://github.com/Arrow-air/svc-storage"
tag = "v0.9.0-develop.10"

[[example]]
name = "rest"

[dev-dependencies]
hyper = { version = "0.14", features = ["full"] }
tokio = { version = "1.20", features = ["full"] }
